const products = [
    {
      id: 1,
      image: 'https://images.pexels.com/photos/1407354/pexels-photo-1407354.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      productName: ' Black-and-white Adidas Sneakers ',
      category: 'shoes',
      price: 2999,
      quantity: 10,
    },
    {
      id: 2,
      image: 'https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      productName: 'Silver Linked  Watch',
      category: 'Watch',
      price: 30000,
      quantity: 15,
    },
    {
      id: 3,
      image: 'https://images.pexels.com/photos/904350/pexels-photo-904350.jpeg?auto=compress&cs=tinysrgb&w=600',
      productName: 'White and Blue Floral Sling Bag',
      category: 'Bag',
      price: 50000,
      quantity: 8,
    },
    {
      id: 4,
      image: 'https://images.pexels.com/photos/13570143/pexels-photo-13570143.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      productName: 'Black iPhone on Black Surface',
      category: 'Phone',
      price: 90000,
      quantity: 5,
    },
    {
      id: 5,
      image: 'https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      productName: ' Turned on Ipad',
      category: 'Ipad',
      price: 50000,
      quantity: 10,
    },
    {
      id: 6,
      image: 'https://images.pexels.com/photos/2647714/pexels-photo-2647714.jpeg?auto=compress&cs=tinysrgb&w=600',
      productName: 'Green-leafed Table',
      category: 'Furniture',
      price: 10000,
      quantity: 15,
    },
    {
      id: 7,
      image: 'https://images.pexels.com/photos/701877/pexels-photo-701877.jpeg?auto=compress&cs=tinysrgb&w=600',
      productName: 'Black Framed Hippie Sunglasses',
      category: 'Sunglasses',
      price: 1000,
      quantity: 8,
    },
    {
      id: 8,
      image: 'https://images.pexels.com/photos/815494/pexels-photo-815494.jpeg?auto=compress&cs=tinysrgb&w=600',
      productName: 'Black Cordless Headphones',
      category: 'Headphones',
      price: 2000,
      quantity: 5,
    },
  ];
  
  export default products;